### ISSUE TITLE
Moving the original movie files crashes the viewTracks method

### ISSUE THREAD

**Issue by vladimirg** [itskov/MultiAnimalTrackerSuite#4]
Steps to reproduce:
1) Create a track file from the movie.
2) Move the original movie to another folder.
3) Open the track file created in step (1) as described in the manual.
4) Run  `tracker.viewTracks(tracks,[1, tracker.numberOfFrames]);`.
There's a rather uninformative error, caused by an empty VideoReader object. This is happening because the `tracker.tracker.videoFileName` property no longer points to the actual video (which was moved in step (2)).

At the very least, an informative error should appear. A more user-friendly option is to open a dialog, prompting the user to find the lost video.

**Comment by itskov** [comment]
The tracker object should be told you moved the file to somewhere else.
I'll show you how its done. One liner.

**Comment by vladimirg** [comment]
Provisional solution:
1) Load the TrackingInfo file, make sure not to stop on errors.
2) Change the `tracker.videoFileName` field to the correct path.
3) Save the `tracker` and `tracks` variables back into the file.
(If you want to work with the tracker immediately, run `tracker.initialize`.)

Next load should work smoothly.
