### ISSUE TITLE
Where can I find the demo videos and the labelled files of BMC article?

### ISSUE THREAD

**Issue by oaishi** [itskov/MultiAnimalTrackerSuite#6]
Hello,

Thank you for your materials. In the journal article page of your work, there are some output examples of your work. I wanted to use the labelled videos for thesis purpose. Can you kindly tell me where I can find them? Also, I needed the label information (i.e: the position of each detected animal of each frame). Can you kindly provide me with this information?

Thank you!

**Comment by itskov** [comment]
Hi !
I apologize. I don't have the tracks for those videos.  :(

**Comment by oaishi** [comment]
No worries. Thanks for your reply!
